### ISSUE TITLE
メディウム記事

### ISSUE THREAD

**Issue by yukiohgishi** [furuhashilab/hackathon-grareco#3]

**Comment by Ayaka0324** [comment]
[medium記事](https://medium.com/furuhashilab/%E5%9B%BD%E5%9C%9F%E5%9C%B0%E7%90%86%E9%99%A2-%E5%85%AC%E5%BC%8Ftwitter-%E3%82%A4%E3%83%A9%E3%82%B9%E3%83%88%E5%8C%96-23f60a33ff0a)
